import type { Metadata } from "next";
import { Inter, Space_Grotesk } from "next/font/google";
import "./globals.css";
import RootLayout from "@layouts/root-layout";
const inter = Inter({
  variable: "--font-primary",
  subsets: ["latin"],
});

const grotesk = Space_Grotesk({
  variable: "--font-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${grotesk.variable} antialiased font-inter bg-slate-200`}
      >
        <RootLayout>{children}</RootLayout>
      </body>
    </html>
  );
}
